run:
  tests: false
  skip-dirs:
    - internal
linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 5
    min-occurrences: 3
  depguard:
    list-type: blacklist
  goimports:
    local-prefixes: github.com/getndazn/dx-drone-to-gha
  gocritic:
    settings:
      rangeValCopy:
        sizeThreshold: 512
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - singleCaseSwitch #nice for expandability,
      - hugeParam #maybe disable for high performance lambdas
      - appendCombine #multiple appends can be nice visually
  funlen:
    lines: 100
    statements: 52

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - gosec
    - gosimple
    - ineffassign
    - nakedret
    - exportloopref
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - govet

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G306: Expect WriteFile permissions to be 0600 or less"
