linters:
  enable:
    - goimports
    - gci
    - containedctx
    - contextcheck
    - dupl
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gomnd
    - misspell
    - revive
    - unparam
    - wrapcheck
linters-settings:
  goimports:
    local-prefixes: github.com/yogeshlonkar/yrl
  wrapcheck:
    ignoreSigRegexps:
      - '.*github.com/yogeshlonkar/yrl/.*'
    ignorePackageGlobs:
      - github.com/yogeshlonkar/yrl/*
  gocyclo:
    min-complexity: 12
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - dot
      - prefix(github.com/yogeshlonkar/yrl) # local packages.
    custom-order: true
